spring:
  main:
    web-application-type: none
  application:
    name: quadstore

  flyway:
    schemas: quadstore

  jackson:
    default-property-inclusion: NON_NULL

  dataSource:
    url: jdbc:postgresql://localhost:5432/quadstore?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    hikari:
      maxIdle: 10
      max-active: 50
      max-wait: 10000

  hermes:
    snomedBaseUrl: http://localhost:8088/v1/snomed/concepts